#!/usr/bin/env bash

SYNCTHING_USER="$1"

SYNCTHING_UID="$(id -u "$SYNCTHING_USER")"
SYNCTHING_CONFIG_DIR="/home/$SYNCTHING_USER/.config/syncthing"
SYNCTHING_DOCKER_ENV_FILE="/home/$SYNCTHING_USER/.config/syncthing/docker_env"

mkdir -p "$SYNCTHING_CONFIG_DIR"
touch "$SYNCTHING_DOCKER_ENV_FILE"

grep -e '^PUID=' "$SYNCTHING_DOCKER_ENV_FILE" || echo "PUID=$SYNCTHING_UID" >> "$SYNCTHING_DOCKER_ENV_FILE"
grep -e '^PGID=' "$SYNCTHING_DOCKER_ENV_FILE" || echo "PGID=$(id -u "$SYNCTHING_USER")" >> "$SYNCTHING_DOCKER_ENV_FILE"
grep -e '^LISTEN_PORT=' "$SYNCTHING_DOCKER_ENV_FILE" || echo "LISTEN_PORT=$((22000 + "$SYNCTHING_UID" - 1000))" >> "$SYNCTHING_DOCKER_ENV_FILE"
grep -e '^LOCAL_ANNOUNCE_PORT=' "$SYNCTHING_DOCKER_ENV_FILE" || echo "LOCAL_ANNOUNCE_PORT=$((21000 + "$SYNCTHING_UID" - 1000))" >> "$SYNCTHING_DOCKER_ENV_FILE"
grep -e '^WEBUI_PORT=' "$SYNCTHING_DOCKER_ENV_FILE" || echo "WEBUI_PORT=$((28000 + "$SYNCTHING_UID" - 1000))" >> "$SYNCTHING_DOCKER_ENV_FILE"
